services:
  host: "0.0.0.0"
  port: 8080

config:
  env: prod
  csrf:
    secret: kNaV2rHX12L4bUuhEEXQ9plJbjtYN2P7
    age: 600 #seconds
    domain: ".idtecsi.my.id"
    path: "/"
  auth:
    uri: "https://sso.idtecsi.my.id"
    path:
      token: "/auth/api/token"
      login: "/auth/api/login"
      auth: "/auth/api/authorize"
  url:
    redirectFe:
      login: "https://sso.idtecsi.my.id/login"
    default:
      home: "https://inventory.idtecsi.my.id" # ganti ke fe
      callbackUrl: "https://inventory.idtecsi.my.id/v1/api/callback"
  verifier:
    age: 300 #seconds
    domain: ".idtecsi.my.id"
    path: "/"
    secure: true
    httponly: true
  refreshToken:
    age: 172800 #seconds
    domain: ".idtecsi.my.id"
    path: "/"
    secure: false
    httponly: true

secret:
  sso:
    public: "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvXsnS6kT7zD5ebOS57gFv4+NHZx5\nq47xQgmZZUn5ZEd/Me8CPuVv+nCW2VY3cM1z3dcZ6c9LGokCRoIZ5s190g==\n-----END PUBLIC KEY-----"
  inventory:
    key: ES256
    private: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIHhNCyKahW3YrJcf+zcPm6MwJgKmXh3L7F6c9XV952W2oAoGCCqGSM49\nAwEHoUQDQgAE7tq65PUAh1NAomx9wxjwPwHt52G2DxG2YYcNOdAtK6DFdsHH90sp\nhx663EI6XM/uFHAAhX1zbL39LgVT50PEnQ==\n-----END EC PRIVATE KEY-----"
    public: "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7tq65PUAh1NAomx9wxjwPwHt52G2\nDxG2YYcNOdAtK6DFdsHH90sphx663EI6XM/uFHAAhX1zbL39LgVT50PEnQ==\n-----END PUBLIC KEY-----"

database:
  read:
    driver: postgresql
    host: 192.168.0.251
    port: 5432
    database: inventory
    schema: inventory
    username: inventory
    password: asd123qwe
  write:
    driver: postgresql
    host: 192.168.0.251
    port: 5432
    database: inventory
    schema: inventory
    username: inventory
    password: asd123qwe