services:
  host: localhost
  port: 8080

config:
  csrf:
    age: 600 #seconds
    domain: "localhost"
    path: "/"
  oauth:
    age: 3600 #seconds
    domain: "localhost"
    path: "/"

database:
  read:
    driver: postgresql
    host: localhost
    port: 5432
    database: inventory
    schema: inventory
    username: ryuze
    password: asd123qwe
  write:
    driver: postgresql
    host: localhost
    port: 5432
    database: inventory
    schema: inventory
    username: ryuze
    password: asd123qwe