database:
  read:
    # host: 192.168.0.250
    host: localhost
    port: 5432
    database: postgres
    schema: inventory
    username: postgres
    # password: asd123qwe
    password: postgres
  write:
    # host: 192.168.0.250
    host: localhost
    port: 5432
    database: postgres
    schema: inventory
    username: postgres
    # password: asd123qwe
    password: postgres