// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID          string
	Name        string
	Description string
	InsertDate  pgtype.Timestamp
	UpdateDate  pgtype.Timestamp
	DeleteDate  pgtype.Timestamp
}

type GlobalItem struct {
	ID         string
	Name       string
	InsertDate pgtype.Timestamp
	UpdateDate pgtype.Timestamp
	DeleteDate pgtype.Timestamp
}

type Item struct {
	ID           string
	GlobalItemID pgtype.Text
	CategoryID   pgtype.Text
	Name         string
	Qty          int32
	LocationID   pgtype.Text
	PositionID   pgtype.Text
	InsertDate   pgtype.Timestamp
	UpdateDate   pgtype.Timestamp
	DeleteDate   pgtype.Timestamp
}

type Location struct {
	ID          string
	Name        string
	Address     string
	Description pgtype.Text
	InsertDate  pgtype.Timestamp
	UpdateDate  pgtype.Timestamp
	DeleteDate  pgtype.Timestamp
}

type Position struct {
	ID         string
	LocationID pgtype.Text
	InsertDate pgtype.Timestamp
	UpdateDate pgtype.Timestamp
	DeleteDate pgtype.Timestamp
}
